[package]
name = "bly"
version = "0.1.0"
authors = ["nischayv <nischay.v@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
